### ISSUE TITLE
How to set password

### ISSUE THREAD

**Issue by pniedzwiedzinski** [nix-community/nixos-anywhere#404]
Hi,
Feeling like asking a newbie question, but I was unable to find any information about when to set up password during the installation process with nixos-anywhere (I'm deploying to laptop with USB installer stick).
Install was successful and I can boot to the new system, but no user has password set up. I know, I can again boot into the USB stick and `passwd --root`, but it doesn't sound like the "anywhere" solution. How do you do that?

If it's relevant, I'm running:
```
nix run github:nix-community/nixos-anywhere -- --flake github:pniedzwiedzinski/dots#x220 nixos@laptop
```

**Comment by sedlund** [comment]
you should manage the users on it like any other nixos machine.  have a look at the manual:

https://nixos.org/manual/nixos/stable/#sec-user-management

and specifically [users.users.\<name\>.hashedPassword](
https://search.nixos.org/options?channel=24.05&show=users.users.%3Cname%3E.hashedPassword&from=0&size=50&sort=relevance&type=packages&query=users.users.%3Cname%3E.hashedPassword)

since the machine is already installed and hopefully you have configured a ssh key to be able to connect to it remotely.  you could update your configuration push a password to it. 

Since you are using flakes you would use:

> nixos-rebuild switch --flake github:pniedzwiedzinski/dots#x220 nixos@laptop`

(see: https://github.com/nix-community/nixos-anywhere/blob/main/docs/quickstart.md#finished)

**Comment by pniedzwiedzinski** [comment]
Thanks, I wasn't aware of the `hashedPassword` option
