### ISSUE TITLE
Skip kexec if Nixos is detected?

### ISSUE THREAD

**Issue by ritiek** [nix-community/nixos-anywhere#405]
Hello!

I've been trying to nixos-anywhere to a x86_64-linux target machine having 512 MB physical RAM from my host machine. The installer runs of out of memory if I first boot the target machine into the official minimal installer ISO and run nixos-anywhere from my host machine to this target machine.

So I generated a custom minimal ISO using [nixos-generators](https://github.com/nix-community/nixos-generators) with zram enabled using the following module:
```nix
{
  networking.hostName = "minimal-iso";
  
  users.users.root.openssh.authorizedKeys.keys = [ "my-ssh-key" ];
  
  services.openssh = {
    enable = true;
    startWhenNeeded = true;
    settings = {
      PermitRootLogin = "yes";
      PasswordAuthentication = false;
    };
  };
  
  powerManagement.cpuFreqGovernor = "performance";
  
  zramSwap = {
    enable = true;
    memoryPercent = 100;
  };
  
  nix.settings.auto-optimise-store = true;
  
  system.stateVersion = "24.05";
}
```
Building the above configuration in `install-iso` format generates an ISO image. Booting into this ISO on my target machine and then performing nixos-anywhere from my host machine looks to succeed now!

--------------------

However, I also noticed that if build the same configuration in `iso` format, the resulting ISO image is much smaller; ~400 MB (vs ~1.2GB when using `install-iso` format).

If I boot from this image on the target machine and then perform nixos-anywhere from my host machine, the installer again runs of out memory as it seems to execute kexec by default (which seems unnecessary to me in this case as target is already booted into Nixos). The installation succeeds if I omit `kexec` while explicitly passing `phases` (`--phases disko,install,reboot`).

Given this, curious shouldn't it be enough to check whether the target OS is Nixos when deciding to skip kexec (no need to check whether it's an installer image on top of Nixos):

https://github.com/nix-community/nixos-anywhere/blob/3fb834da466b75300a9141f9a68869c56fbd28f3/src/nixos-anywhere.sh#L463-L466

```diff
- if [[ ${isKexec} == "y" ]] || [[ ${isInstaller} == "y" ]]; then
+ if [[ ${isKexec} == "y" ]] || [[ ${isNixos} == "y" ]]; then
```

**Comment by sedlund** [comment]
the [installer images](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/installer/cd-dvd/installation-cd-base.nix) are built with all kernel [modules and firmware](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/profiles/all-hardware.nix) enabled so that `nixos-generate-config` can probe to generate a `hardware-configuration.nix`

**Comment by cowboyai** [comment]
this makes sense...
so, the question then is... How do I ensure my custom build sets isInstaller = true; or causes it to be set through evaluation?
just include certain packages, or use an installer image as base?  I currenty use `hardened` this way in configuration.nix:

```nix
  imports =
    [
      #self.inputs.disko.nixosModules.disko
      "${modulesPath}/profiles/hardened.nix"
      ./modules/hardware-configuration.nix
      ...
```
I know my hardware. I already created hardware-configuration.nix (I use commodity hardware, same model and mfg)
I want to build my own image, and be certain isInstaller = true; since it is, in fact, an installer, tuned to this machine for running nixos-anywhere.

I have the same issue with kexec failing, when kexec is not required.

I have looked in options and several manuals and can't find isInstaller referenced. (searching for `installer` is a bit problematic.)

**Comment by cowboyai** [comment]
so I include 
```
system.nixos.variant_id = lib.mkDefault "installer";
```
in my configuration.nix and that sets it as an installer?

**Comment by cowboyai** [comment]
yes, this works. so, mark this as solution and close the issue, thank you for clarifying isInstaller.
