### ISSUE TITLE
nixos-facter not available

### ISSUE THREAD

**Issue by elliott-farrall** [nix-community/nixos-anywhere#423]
I am trying to install to a machine that is running the minimal nixos iso and generate the hardware config using nixos-facter. However, I keep getting
```
aborted: nixos-facter is not available in booted installer. You may want to boot an installer image from here instead: https://github.com/nix-community/nixos-images
```
I have tried visiting the page but couldn't find anything on there that helped.

**Comment by sedlund** [comment]
Just to follow up.  If you pre booted a ln official nixos installer it will not have nixos-facter and nixos-anywhere will use this environment rather than running kexec.   If the target machine was booted into a Linux OS  it would have kexec'd into an image that has nixos-facter available.  So in your situation it is easiest to just opt to use nixos-generate-config.

**Comment by thislooksfun** [comment]
I know this is an old issue, so I can open a new one if preferred, but why not have the installer install `nixos-factor` (or run via `nix-shell -p nixos-facter`) if it is missing? That way it could work on all systems out-of-the-box.

**Comment by elliott-farrall** [comment]
> I know this is an old issue, so I can open a new one if preferred, but why not have the installer install `nixos-factor` (or run via `nix-shell -p nixos-facter`) if it is missing? That way it could work on all systems out-of-the-box.

I was also wondering why this is not the case.
